---
title: "Social Survey"
author: "Paul Hamby "
date: "11/13/17"
output:
  html_document: default
---

```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
source("Import_GSS_2014_haven.R")
```
<!-- We recommend you use git branches -- create a separate branch for each major section i.e. Introduction, Methods, Results, Inferential Results, and Discussion and Conclusions - leave the YAML block untouched until the final merge where you put in your own name !-->

# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?!-->   
In this study, we are observing several different varaibles and comparing them to one main varaible. In this case, the main varaible would be gun ownership which, we would compare to other varaibles. The other varaibles include the beleif in the big bang theory, race, education level, and the belief in God. Our main question when conducting this research is, whether or not there is a relationship between these varaibles. It is possible that there is a direct relationship involved between some of these variables but, it is also possible for there not to be. 
####This study deals with questions about possible relationships between gun ownership and race, sex, political views, opinions on capitol punishment and belief in god. The data is from the 2014 general social survey.



# Methods

<!--Decide on your methods:  use "variable analysis" or other appropriate descriptors.  Make sure to choose at least one graphical method and at least one numerical method.!-->

In order for us to be able to observe if there is a relationship between these varaibles, we will need to use the appropraiate tools. For this research project, we wil be using data from the General Social Survey from the year 2014. However, the file that we currently have contains information between the year 2010, and the year 2014. Therefore, we are going to condense the data by using the given code which will allow us to observe only the data from 2014. IN order for us to be able to physcially observe the data, we will be running barcharts that will be compairing the main varaible (gun ownership) with the other varaibles. That way, we are physically able to see if there is a direct relationship between the variables. For the inferential results, we will be running a chisquared test in order for us to see if there is a direct relationship between the varibles. With the use of the barcharts, we will be able to numerically express if there is a direct relationship between the varaibles. 
#Results

<!--Divide this section into two sub-sections:  One for your descriptive  results and one for your inferential results.!-->

## Descriptive Results

### Graphical Descriptive Results

<!--Graphical results here.  Make sure to show your code.  Provide appropriate labels for axes, giving units if possible, and provide a good title for the graph, too.  Use the graphical results to describe the patterns if any that exist in the data as focused toward the research question!-->

### Numerical Descriptive Results

<!--Numerical results go here. Use the numerical results to describe the patterns if any that exist in the data as focused toward the research question!-->

# Inferential Results

<!--State hypothesis clearly.  Make sure your discussion of the inferential test covers all the aspects that the test output produces, such as test statistic, p-value etc.  Make a decision about the null hypothesis, explain the assumptions on which the selected test/procedure was based, and why the chosen procedure satisfys the assumptions and is appropriate to answer the research question!-->


# Discussion and Conclusion

<!--Discussion and conclusion here.  If you found a relationship be sure to consider whether the relationship occurs because one of the variables causes the other, or whether they perhasps are related for some other reason.  Watch the chapter 6 videos from the GeorgeTown videos collection.!-->
